config/routes.rb
Jobs::Application.routes.draw do
  resources :users, only: [:show, :create]
  resources :sessions, only: [:create]
  resources :projects, only: [:index, :show, :new, :create]

  resources :projects do
    resources :sprints, only: [:show, :create, :index, :new]
  end

  resources :sprints do
    resources :works, only: [:create]
  end

  resources :works, only: [:destroy]
  resources :works do
    member do
      post :checkout
      post :finish
      post :review
    end
  end

  match '/signin', to: 'sessions#new'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  root to: 'home#index'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Project < ActiveRecord::Base
  attr_accessible :name, :description

  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :sprints

  validates :name,
    presence: true,
    length: { maximum: 255 }
  validates :description,
    length: { maximum: 255 }

  default_scope order: 'created_at DESC'
  scope :with_creator, joins(:creator)

  def self.search(search, page)
    if search
      with_creator.where("name LIKE ?", "%#{search}%").paginate(page: page, per_page: 10)
    else
      with_creator.paginate(page: page, per_page: 10)
    end
  end

  def current_sprint
    logger.debug "sprints: #{sprints.count}"
    sprints.first
  end
end

app/models/sprint.rb
# == Schema Information
#
# Table name: sprints
#
#  id         :integer          not null, primary key
#  project_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sprint < ActiveRecord::Base
  attr_accessible :description

  belongs_to :project
  has_many :works

  default_scope :order => "created_at DESC"
  scope :recent, limit(5)

  before_save :create_name

  def prepare_name
    name.nil? ? "sprint #{project.sprints.count + 1}" : name
  end

  def uncheck_works
    works.uncheck
  end

  def checked_out_works
    works.started
  end

  def review_works
    works.review
  end

  def complete_works
    works.complete
  end

  private 

  def create_name
    self.name = "sprint #{project.sprints.count + 1}" if name.nil?
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  validates :name, 
            presence: true,
            length: { maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  validates :password,
            presence: true,
            confirmation: true
  validates :password_confirmation,
            presence: true

  before_save :create_remember_token

  has_many :projects

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :name, :description

  belongs_to :sprint
  belongs_to :checker, class_name: "User", foreign_key: :checker_id

  scope :uncheck, where(state: :uncheck)
  scope :started, where(state: :started)
  scope :review, where(state: :review)
  scope :complete, where(state: :complete)

  def check_out_by!(user)
    self.checker = user
    self.state = "started"
    save!
  end

  def finish!
    self.state = "complete"
    save!
  end

  def review!
    self.state = "review"
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = current_user.projects.paginate(page: params[:page], per_page: 10) if signed_in?
  end
end

app/controllers/projects_controller.rb
# encoding: utf-8

class ProjectsController < ApplicationController
  before_filter :sign_in_user

  def index
    @projects = Project.search(params[:search], params[:page])
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(params[:project])
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  def sign_in_user
    redirect_to signin_path, notice: "访问被拒绝，你可能没有权限或登录" unless signed_in?
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash.now[:error] = "帐号或密码错误"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.new
  end

  def create
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.create(params[:sprint])
    @sprint.save
    redirect_to @project
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def create
    @sprint = Sprint.find(params[:sprint_id])
    @work = @sprint.works.create!(params[:work])
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def checkout
    @work = Work.find(params[:id])
    @work.check_out_by!(current_user)
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def finish
    @work = Work.find(params[:id])
    @work.finish!
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def review
    @work = Work.find(params[:id])
    @work.review!
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def destroy
    Work.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render 'destroy', locals: { id: params[:id] } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
# encoding: utf-8

module ProjectsHelper
  def project_simple_info(project)
    content_tag(:em) do
      html = link_to project.creator.name, project.creator
      html << "创建于#{time_ago_in_words(project.created_at)}前"
    end
  end

  def search_form
    form_tag(projects_path, method: :get) do
      content_tag(:div, class: "input-append center") do
        html = search_field_tag(:search, nil, class: "span8")
        html << submit_tag('Go', class: 'btn')
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by_remember_token(session[:remember_token])
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_in(user)
    session[:remember_token] = user.remember_token
    current_user = user
  end

  def sign_out
    session.delete :remember_token
    cookies.delete :remember_token
    current_user = nil
  end
end

app/views/home/index.html.haml
- provide :title, '主页'
- if signed_in?
  .box-gray.span12
    .page-header
      %h1 我的项目
    = render partial: 'projects/project', collection: @projects
    = will_paginate @projects
- else
  .row.hero-unit
    %h1 欢迎
    %p
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    .center
      = link_to '注册', signup_path, class: 'btn btn-large btn-primary'

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to 'Jobs', root_path, id: 'logo'
      %nav
        %ul.nav.pull-right
          %li= link_to '主页', root_path
          - if signed_in?
            %li= link_to 'Projects', projects_path
            %li.dropdown
              %a.dropdown-toggle{ data: { toggle: 'dropdown' }, href: '#' }
                = current_user.name
                %b.caret
              %ul.dropdown-menu{ role: 'menu' }
                %li= link_to '退出', signout_path, method: :delete
          - else
            %li= link_to '注册', signup_path
            %li= link_to '登录', signin_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobs | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <a href="#" class="close", data-dismiss="alert"><i class="icon-remove"></i></a>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/projects/_project.html.haml
= div_for(project) do
  .title
    %h2= link_to project.name, project
    %span= "(#{pluralize(project.sprints.count, 'sprint')})"
  .info
    %p.description= project.description
    = project_simple_info(project)

app/views/projects/index.html.haml
- provide :title, 'Projects'

.row-fluid
  .span9.box-gray
    .page-header
      %h1 Projects
    .projects
      = render @projects
    = will_paginate @projects
  .span3.box.sidebar
    %h1 搜索
    %p
      = search_form
  .span3.box.sidebar
    %h1 新建项目
    %p.center= link_to '新建', new_project_path, class: 'btn btn-primary'

app/views/projects/new.html.haml
- provide :title, '新建项目'

.row-fluid
  .span9.box
    %fieldset
      %legend 新建项目
      = form_for @project, html: { class: 'form-horizontal' } do |f|
        = render 'shared/error_messages', object: f.object
        .control-group
          = f.label :name, '项目名称', class: 'control-label'
          .controls
            = f.text_field :name, class: 'span8'
        .control-group
          = f.label :description, '项目描述', class: 'control-label'
          .controls
            = f.text_area :description, rows: 6, class: 'span8'
        .form-actions
          = f.submit '提交', class: 'btn btn-primary'

app/views/projects/show.html.haml
- provide :title, @project.name

.row-fluid
  .span9.box-gray
    .page-header.project-title
      %h1= @project.name
      = link_to "new sprint", new_project_sprint_path(@project), class: 'btn btn-primary'
    - if @project.current_sprint
      .current-sprint{ id: "sprint-#{@project.current_sprint.id}" }
        %h2 当前Sprint
        = render @project.current_sprint
  .span3.box.sidebar
    %h1 历史
    %p
      %ul
        - @project.sprints.recent.each do |sprint|
          %li= link_to sprint.name
      .span10
        .pull-right
          = link_to '更多...', project_sprints_path(@project)

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-block.alert-error
    %a.close{ data: { dismiss: 'alert' }, href: '#', class: 'icon-remove' }
    %p
      %strong= "有#{object.errors.count}处问题导致无法提交"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/sprints/_sprint.html.haml
.sprint
  %ul.nav.nav-tabs#sprint-tab
    %li.active
      %a{ href: "#new", "data-toggle" => 'tab' }
        new(
        %span#new-count= sprint.uncheck_works.count
        )
    %li
      %a{ href: "#check-out", "data-toggle" => 'tab' } 
        check out (
        %span#checkout-count= sprint.checked_out_works.count
        )
    %li
      %a{ href: "#review", "data-toggle" => "tab" }
        review (
        %span#review-count= sprint.review_works.count
        )
    %li
      %a{ href: "#complete", "data-toggle"=> "tab" } 
        complete (
        %span#complete-count= sprint.complete_works.count
        )
  .tab-content
    .tab-pane.active#new
      %table
        = render sprint.uncheck_works
    .tab-pane#check-out
      %table
        = render sprint.checked_out_works
    .tab-pane#review
      %table
        = render sprint.review_works
    .tab-pane#complete
      %table
        = render sprint.complete_works

  .new-work
    = form_for(:work, url: sprint_works_path(sprint), html: { method: :post }, remote: true) do |f|
      = f.text_field :name, placeholder: "名称", class: 'name-field'
      = f.text_field :description, placeholder: "描述。。。", class: 'des-field'

      = f.submit 'new work item', class: 'btn btn-small'

app/views/sprints/new.html.haml
- provide :title, "新的Sprint"

.row-fluid
  .span9.box
    %fieldset
      %legend= @sprint.prepare_name
      = form_for @sprint, url: project_sprints_path(@project), html: { class: 'form-horizontal' } do |f|
        = render 'shared/error_messages', object: f.object
        .control-group
          = f.label :description, '描述', class: 'control-label'
          .controls
            = f.text_area :description, rows: 6, class: 'span8'
        .form-actions
          = f.submit '提交', class: 'btn btn-primary'

app/views/users/new.html.haml
- provide :title, '注册'

.form-wrapper
  %legend 注册新用户
  = form_for @user, html: { class: 'form-horizontal' } do |f|
    = render 'shared/error_messages', object: f.object
    .control-group
      = f.label :name, '姓名', class: 'control-label'
      .controls
        = f.text_field :name, size: 40
    .control-group
      = f.label :email, 'Email', class: 'control-label'
      .controls
        = f.email_field :email
    .control-group
      = f.label :password, '密码', class: 'control-label'
      .controls
        = f.password_field :password
    .control-group
      = f.label :password_confirmation, '确认密码', class: 'control-label'
      .controls
        = f.password_field :password_confirmation
    .pull-right
      = f.submit '提交注册信息', class: 'btn btn-primary'

app/views/works/_work.html.haml
%tr.work{ id: "work-#{work.id}" }
  %td.work_name
    %span.fixed= work.name
  %td.work_des
    %span.fixed= work.description
    %td.action
      = link_to work, method: :delete, remote: true do
        %i.icon-remove
      %span
        -case work.state
        -when "uncheck"
          = link_to "check out", checkout_work_path(work), method: :post, class: 'btn btn-mini btn-info', remote: true 
        -when "started"
          = link_to 'review', review_work_path(work), method: :post, class: 'btn btn-mini btn-info', remote: true
        -when "review"
          = link_to 'finish', finish_work_path(work), method: :post, class: 'btn btn-mini btn-info', remote: true

app/views/works/checkout.js.erb
$('#new #work-<%= @work.id %>').remove();
$('#new-count').text($('#new tr').length);

$('#sprint-tab li:eq(1) a').tab('show');

$('#check-out table').append('<%= j render(@work) %>');
$('#checkout-count').text($('#check-out tr').length);

app/views/works/create.js.erb
$('#sprint-tab li:eq(0) a').tab('show');

$('#new table').append('<%= j render(@work) %>');
$('#new-count').text($('#new tr').length);

app/views/works/destroy.js.erb
$('#work-<%= id %>').remove();
$('#new-count').text($('#new table tr').length);
$('#checkout-count').text($('#check-out table tr').length);
$('#review-count').text($('#review table tr').length);
$('#complete-count').text($('#complete table tr').length);

app/views/works/finish.js.erb
$('#review #work-<%= @work.id %>').remove();
$('#review-count').text($('#review tr').length);

$('#sprint-tab li:eq(3) a').tab('show');

$('#complete table').append('<%= j render(@work) %>');
$('#complete-count').text($('#complete tr').length);

app/views/works/review.js.erb
$('#check-out #work-<%= @work.id %>').remove();
$('#checkout-count').text($('#check-out tr').length);

$('#sprint-tab li:eq(2) a').tab('show');

$('#review table').append('<%= j render(@work) %>');
$('#review-count').text($('#review tr').length);